#!/bin/bash

SINCE=""
MERGE=" | grep -v ^Merge"
function menu_help {
	echo "-d   --days               Last days"
	echo "-w   --weeks              Last weeks"
	echo "-a   --air                Only AIR-"
	echo "-c   --csi                Only CSI-"
	echo "-g   --grep               Any string"
	echo "-m   --branch             Merged"
	echo "-h,? --help               Help"
}


while test $# -gt 0
	do
		case "$1" in
			-d|--days)
				shift
				if [[ $1 =~ [0-9]+ ]]
                then
                    SINCE="--since=$1.days"
                fi;
				shift
				;;
			-w|--weeks)
				shift
				if [[ $1 =~ [0-9]+ ]]
                then
                    SINCE="--since=$1.weeks"
                fi;
				shift
				;;
		    -a|--air)
		    	shift
                   AIR="| grep -i ^AIR-"
            	;;
		    -c|--csi)
		    	shift
                   CSI=" | grep -i ^CSI-"
            	;;
            -g|--grep)
                shift
                   GREP=" | grep $1"
               	shift
               	;;
			-m|--merged)
				shift
                   MERGE=" | grep -i ^Merge"
				;;
			?|-h|--help)
            	shift
            	    menu_help
            	exit 0
            	;;
            *)
                echo "$1 is not a recognized option"
                exit 0
            ;;
		esac
done

GIT="git log --date=short --pretty=\"%s |%Cgreen %an %Creset| %cD |%Cred %ar %Creset\" $SINCE $MERGE $CSI $AIR $GREP"
eval $GIT
